//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYS.Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAdresTipleri
    {
        public int IletisimTipiId { get; set; }
        public string IletisimTipi { get; set; }
        public string Adres { get; set; }
        public string EvTelefonu { get; set; }
        public string Istelefonu { get; set; }
        public string CepTelefonu { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silik { get; set; }
        public byte[] KayitVersiyonu { get; set; }
    }
}
